'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SinglePlayerApartmentTool.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property american() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("american", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property apartment() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("apartment", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property car() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("car", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property chinese() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chinese", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property clothing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clothing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property french() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("french", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property garage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("garage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property german() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("german", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property italian() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("italian", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property japanese() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("japanese", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property korean() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("korean", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mexican() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mexican", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property michael() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("michael", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property no_image_thumb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("no_image_thumb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property polish() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("polish", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property portuguese() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portuguese", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property russian() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("russian", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property spa_header_1024x229() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spa_header-1024x229", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property spa_header_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spa_header-2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property spanish() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spanish", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to VehicleName &quot;&quot;
        '''VehicleModel &quot;&quot;
        '''PrimaryColor &quot;&quot;
        '''SecondaryColor &quot;&quot;
        '''PearlescentColor &quot;&quot;
        '''HasCustomPrimaryColor &quot;&quot;
        '''HasCustomSecondaryColor &quot;&quot;
        '''CustomPrimaryColorRed &quot;&quot;
        '''CustomPrimaryColorGreen &quot;&quot;
        '''CustomPrimaryColorBlue &quot;&quot;
        '''CustomSecondaryColorRed &quot;&quot;
        '''CustomSecondaryColorGreen &quot;&quot;
        '''CustomSecondaryColorBlue &quot;&quot;
        '''RimColor &quot;&quot;
        '''HasNeonLightBack &quot;&quot;
        '''HasNeonLightFront &quot;&quot;
        '''HasNeonLightLeft &quot;&quot;
        '''HasNeonLightRight &quot;&quot;
        '''NeonColorRed &quot;&quot;
        '''NeonColorGreen &quot;&quot;
        '''NeonColorBlue &quot;&quot;
        '''TyreSmokeColorRed &quot;&quot;
        '''TyreSmokeColorGreen &quot;&quot;
        '''T [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property vehicle() As String
            Get
                Return ResourceManager.GetString("vehicle", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
